### ISSUE TITLE
ERROR runing PPSTM_simple.py on CP2K

### ISSUE THREAD

**Issue by lycheehoo** [Probe-Particle/PPSTM#26] opened 2024-08-27 01:35 UTC
Dear developers, when I tried to run the PPSTM_simple.py to simulate the CP2K calculated outcomes, the error came as below:
```
Reading CP2K MOs from:MOL_AU111-cartesian-mos-1_0.MOLog
Found 5436 MOs spanned by 6438 basis functions centered on 252 atoms.
The Fermi Level:  -4.703134149245  eV; in FHI-AIMS is the Fermi automatically 0.
Traceback (most recent call last):
  File "PPSTM_simple.py", line 208, in <module>
    eigEn1, coefs1, Ratin  = RS.read_CP2K_all(name = files_path + cp2k_name , lvs=cell, fermi=fermi, orbs = sample_orbs, pbc=pbc, cut_min=cut_min, cut_max=cut_max, cut_at=cut_atoms, lower_atoms=lower_atoms, lower_coefs=lower_coefs, spin='alpha');
  File "/public4/home/sc53074/software/PPSTM-master/pyPPSTM/ReadSTM.py", line 584, in read_CP2K_all
    raise Exception
Exception
```
My CP2K input file and PPSTM_simple.py were added, could you please help me find the reason for this error? Thank you very much!
[inputfile.zip](https://github.com/user-attachments/files/16755322/inputfile.zip)

**Comment by ondrejkrejci** [comment] 2024-08-27 07:20
Hi @lycheehoo - I cannot figure that out without the `MOL_AU111-cartesian-mos-1_0.MOLog`. My only guess is that you are once more using too new version of CP2K. If that is a truth, then calculating the `MOL_AU111-cartesian-mos-1_0.MOLog` with an old version, or adapting the code for new version, is probably the best way around.

**Comment by lycheehoo** [comment] 2024-08-27 07:47
Thanks! I used the CP2K 7.1 version, and the first 60 lines of my MOL_AU111-cartesian-mos-1_0.MOLog are shown below:
![image](https://github.com/user-attachments/assets/c0d73f64-4e4d-4559-8dfd-df650c0f4644)

**Comment by ondrejkrejci** [comment] 2024-08-27 07:50
Ok, thank you - the problem is, than the problem is in the code - it does not know any _f_ orbitals. Should not be a problem  in STM - they are (highly probably) not seen. I just need to make small change in the code. I will do it today afternoon (european time) probably.

**Comment by lycheehoo** [comment] 2024-08-27 08:11
Yes, I got it, thanks!

**Comment by ondrejkrejci** [comment] 2024-08-28 09:24
Hi, we have updated the code, so it should work in principle. Please let us know, how does it work now.

**Comment by lycheehoo** [comment] 2024-08-28 11:05
Yes, it runs successfully! Thank you so much!

**Comment by LauriKurki** [comment] 2024-08-28 11:21
Nice! Closing as fixed.

**Closed by LauriKurki** 2024-08-28 11:21 UTC
