### ISSUE TITLE
How to remove the black dots on the dI/dV Mapping?

### ISSUE THREAD

**Issue by WangLulu97** [Probe-Particle/PPSTM#3] opened 2022-09-06 08:08 UTC
Hi！

After using the GUI to produce the image of the dI/dV mapping, there are black and white dots on it which represent the position of the atoms. Is there any method to remove these dots and only leave the mapping image?

Besides, when I use CP2K input, sometimes the mapping image seems flipped from the original xyz position (which makes it cannot align with the black and white dots). Is it common? And may need small post-processing of the output files or the output images?

Thank you!

Best regards,
Lulu

**Comment by WangLulu97** [comment] 2022-09-06 08:45
I think the mapping image is up-down flipped from the original xyz position.

**Comment by LauriKurki** [comment] 2022-09-06 09:35
Hi!

At the moment there is no way to disable atom plotting but we are developing a check box in the GUI for this purpose, should be out soon.

For the second issue, is the mapping flipped always, or only sometimes? Could you provide the input files, please?

Best,
Lauri Kurki

**Comment by LauriKurki** [comment] 2022-09-06 10:03
Hi, 

latest version of PPSTM now has the option to disable atom plotting in the GUI.

Best,
Lauri Kurki

**Comment by WangLulu97** [comment] 2022-09-06 12:07
Hi,

Thanks for your new GUI update! Now I can disable atom plotting in the GUI.

I have tried the new GUI, and it won't flip the image. For the old GUI, it still up-down flips the image. But I think the problem has been fixed by the new GUI.py. So do you still need the input files?

Thank you again! Really thanks!

Best regards,
Lulu

**Comment by LauriKurki** [comment] 2022-09-06 12:12
Hi,

good to hear, in that case I don't need them! My guess is that the issue was caused by a deprecated argument in the plotting function which is also now fixed. 

Closing the issue.

Best,
Lauri

**Closed by LauriKurki** 2022-09-06 12:12 UTC
